= `std` Library Tour

link:./index.html[Table of Contents]

== !

It's time for a tour of some interesting parts in `std`.

We will focus on parts we have not otherwise covered.

== Collections

https://doc.rust-lang.org/std/collections/index.html[`std::collections`]

Contains a number of valuable data structures. In particular:

* https://doc.rust-lang.org/std/vec/struct.Vec.html[`Vec`] for storing sequences of values.
* https://doc.rust-lang.org/std/collections/struct.HashMap.html[`HashMap`] for storing as key value pairs.

When seeking to optimize code other options may be appropriate.

== Entry

https://doc.rust-lang.org/std/collections/hash_map/enum.Entry.html[`std::collections::hash_map::Entry`]

Calling `.entry()` on a `HashMap` accesses this API and allows for 'insert or update' access.

[source,rust]
----
include::./1.rs[]
----

== PhantomData

https://doc.rust-lang.org/std/marker/struct.PhantomData.html[`std::marker::PhantomData`]

Zero-sized type used to mark things that "act like" they own a `T`. These are useful for types which require markers, generics, or use unsafe code.

[source,rust]
----
include::./2.rs[]
----

== Command

https://doc.rust-lang.org/std/process/struct.Command.html[`std::process::Command`]

A process builder, providing fine-grained control over how a new process should be spawned. Used for interacting with other executables.

[source,rust]
----
include::./3.rs[]
----

== Syncronization Primitives

https://doc.rust-lang.org/std/sync/[`std::sync`]

Provides types such a `Mutex`, `RwLock`, `CondVar`, `Arc` and `Barrier`s.

[source,rust]
----
include::./4.rs[]
----

== Read and Write

https://doc.rust-lang.org/std/io/trait.Read.html[`std::io::Read`] & https://doc.rust-lang.org/std/io/trait.Write.html[`std::io::Write`]

Generic read and write functionality to files, sockets, buffers, and anything in between.
Also part of https://doc.rust-lang.org/std/io/prelude/[`std::io::prelude`] (`use std::io::prelude::*`).

[source,rust]
----
include::./5.rs[]
----

== Filesystem Manipulation

https://doc.rust-lang.org/std/fs/[`std::fs`] & https://doc.rust-lang.org/std/path/[`std::path`]

Path handling and file manipulation.

[source,rust]
----
include::./6.rs[]
----
