= Iterators

link:./index.html[Table of Contents]


== !

Rusts iterators are:

-   Lazy
-   Pervasive
-   Potentially infinite

== Where Do They Come From?

-   Collections like `Vec<T>` have an `iter()` function which yields an iterator.
-   Things like `std::net::TcpListener` which provides an iterator of ``TcpStream``s via ``incoming()``.
-   Functions like `str::split` and `str::split_n`
-   Iterators can be implemented on other structures as well.

== Owned iterators

[source,rust]
----
include::./1.rs[]
----

<1> this won't work

== Borrowed iterators

[.notes]
--

- point out that the `for` loop "unwraps" all `Some()`s returned by the iterator for us

--

[source,rust]
----
include::./2.rs[]
----

== Mutably Borrowed iterators

[source,rust]
----
include::./3.rs[]
----

== Conventions

|===
|Owned |Borrowed |Mutably borrowed

|.into_iter()
|.iter()
|.iter_mut()

|===

== Common Uses

== `next()`

[.notes]
--

- ask participants what they think this returns
- point out that we see `Some()`s and a `None` here because there's not for loop to unwrap
  the return value of `next()` for us

--

Iterators can be advanced manually:

[source,rust]
----
include::./4.rs[]
----

== Closures recap

These are equivalent:

// Explanation:
// cols="a,a,a": 3 columns with asciidoc blocks
// options="header": make it a header
// separator=!: otherwise the pipe `|` will bork the table
// Separte option: leave `|` as a separator, and escape it in included snippets.
// ^!: centers the content in the table
[cols="a,a,a", options="header", separator=!]
!====
^! Function
^! Simple closure
^! Multiline closure

!
[source,rust]
----
include::./add_fn.rs[]
----

!
[source,rust]
----
include::./add_closure.rs[]
----

!
[source,rust]
----
include::./add_multiline_closure.rs[]
----
!====

== Add 1

[cols="a,a", options="header", separator=|]
|====
^| Loopy way
^| Simple closure

|
[source,rust]
----
include::./add_one_loop.rs[]
----

|
[source,rust]
----
include::./add_one_iter.rs[]
----
|====
<1> `map` is lazy, `for_each` is eager

== Combinators: `map()`

Transform items as they are evaluated:

[source,rust]
----
include::./5.rs[]
----

== Combinators: `filter()`

Filter out unwanted values, skipping further computation on them:

[source,rust]
----
include::./6.rs[]
----
