= Iterators

link:./index.html[Table of Contents]


== !

Rusts iterators are:

-   Lazy
-   Pervasive
-   Potentially infinite

== Where Do They Come From?

-   Collections like `Vec<T>` have an `iter()` function which yields an iterator.
-   Things like `std::net::TcpListener` which provides an iterator of ``TcpStream``s via ``incoming()``.
-   Iterators can be implemented on other structures as well.

== Common Uses

== `next()`

Iterators can be manually progressed:

[source,rust]
----
include::./1.rs[]
----

== `map()`

Transform items as they are evaluated:

[source,rust]
----
include::./2.rs[]
----

== `filter()`

Filter out unwanted values, skipping further computation on them:

[source,rust]
----
include::./3.rs[]
----

== `fold()`

Reduce a sequence of values down to a single value:

[source,rust]
----
include::./4.rs[]
----

== `cycle()` & `take()`

Cause iterators to repeat, and end early:

[source,rust]
----
include::./5.rs[]
----

== `zip()` & `unzip()`

Join iterators, and split them apart again:

[source,rust]
----
include::./6.rs[]
----

== `max()` & `min()`

[source,rust]
----
include::./7.rs[]
----

== Gotcha

This doesn't work:

[source,rust]
----
include::./8.rs[]
----
Why? (Think about scoping & ownership!)
