= Basic types

link:./index.html[Table of Contents]

== ints

Rust comes with all standard int types, with and without sign

- `i8`, `u8`
- `i16`, `u16`
- `i32`, `u32`
- `i64`, `u64`
- `i128`, `u128`

== Syntactic clarity in specifying numbers

[source,rust]
--
123_456   // underscore as separator
0x12      // prefix 0x to indicate hex value
0o23      // prefix 0o to indicate octal value
0b0001    // prefix 0b to indicate binary value
b'a'      // A single byte character
--

== Architecture-dependent numbers

Rust comes with two architecture-dependent number types:

- `isize`, `usize`

== Casts

Casts between number are possible, *also shortening casts*:

[source,rust]
----
include::./1.rs[]
----

== !

If the size isn't given, or cannot be inferred, ints default to `i32`.

== Overflows

Overflows trigger a trap in Debug mode, but not in release mode. This behaviour can be configured.

== Floats

Rust also comes with floats of all standard sizes: `f32`, `f64`

[source,rust]
----
include::./2.rs[]
----

== Boolean

Boolean in Rust is represented by either of two values: `true` or `false`

== Character

`char` is a https://www.unicode.org/glossary/#unicode_scalar_value[Unicode Scalar Value] being represented as a "single character"

- A literal in single quotes: `'r'`
- Four (4) bytes in size
- Can save more than ASCII, like glyphs, emojis, accented characters etc.

[source,rust]
----
include::./6.rs[]
----


== Arrays

Fixed-size arrays have the following notation:

[source,rust]
----
include::./3.rs[]
----


== Arrays of dynamic size

Arrays of dynamic size in Rust are represented as slices.

Slices carry a pointer to the array and a length. Slices cannot be resized.

[source,rust]
----
include::./4.rs[]
----
