= Advanced Generics: Bounds

link:./index.html[Table of Contents]


== !

Sometimes, we want to constrain a type to certain aspects, while still writing generic code.

To achieve this, we can constrain type parameters.

== !

This can happen at any point where type parameters are used.

== !

Example: `println!("{:?}")` requires Debug

[source,rust]
----
include::./1.rs[]
----

== !

Example: A generic Struct that requires inner values to implement `Debug`

[source,rust]
----
include::./2.rs[]
----

== !

Bounds can also be expressed for implementation targets:

[source,rust]
----
include::./3.rs[]
----

== !

Traits can also directly require prerequisites:

[source,rust]
----
include::./4.rs[]
----

== !

Rust does not allow negative Bounds (Trait A and *not* Trait B)

== Exception: `Sized`

If not specified otherwise, all type parameters carry the bound `Sized` (the type has a statically known memory size). This can be suppressed by using the bound `?Sized`.

[source,rust]
----
include::./5.rs[]
----

== !

This has ergonomic reasons, as passing types by value is common and requires a known size.

== !

Bounds can be used everywhere, which can be used to de-facto constrain types at the call site.

[source,rust]
----
include::./6.rs[]
----

== !

This can be very practical, as this allows expressing different bounds during construction and at call sites.

== !

Bounds are very common in conversion functions.

[source,rust]
----
include::./7.rs[]
----

== Generic implementations

Bounds can be used to constrain the target of an implementation.

[source,rust]
----
include::./8.rs[]
----

== Trait Inheritance

Traits can also request the implementation of other traits and declare default implementations for methods relying on that information.

[source,rust]
----
include::./9.rs[]
----
