= WebAssembly

link:./index.html[Table of Contents]


== What?

WebAssembly(WASM) enables running Rust (among others) in a sandbox environment, including the browser.

WebAssembly is supported as a _compile target_.

== High performance

WASM is built with speed in mind and executes almost as fast as native code.

== The WASM sandbox

In its initial state, WASM does only provide memory and execution, no functionality.

This can be added through the host system in various ways.

== Hello World
[source,wat]
----
include::./1.wat[]
----

== WASM targets in Rust

Rust ships 3 WASM targets:

* wasm32-unknown-emscripten (legacy)
  * ships with an implementations of libc for WASM
* wasm32-unknown-unknown (stable)
  * direct compilation to WASM, with no additional tooling
* wasm32-wasi (in development)
  * WASM with support for _interface types_, a structured way of adding capabilities

== Installation: `rustup` Target

`rustup` allows installing multiple compilation targets.

[source,bash]
----
include::./2.bash[]
----

== Installing a host runtime

[source,bash]
---
include::./3.bash[]
---

* Currently need building from git: https://github.com/bytecodealliance/wasmtime

== Usage: Hello World!

[source,bash]
---
include::./4.bash[]
---

== Usage: The WASI tutorial example

https://github.com/kubkon/rust-wasi-tutorial.git
