= Memory considerations
:revealjs_width: 1920
:revealjs_height: 1080
:source-highlighter: highlightjs

link:./index.html[Table of Contents]


---

`size_of` and `size_of_val` help to inspect the size of a type (in bytes).

[source,rust]
----
include::./1.rs[]
----

== Sizedness

All values in Rust have a fixed or a flexible-sized memory size. The language expresses that through the marker trait `Sized`. `Sized` types have a size known at compile time.

Unsized types *must* be addressed through indirection (e.g. through borrows).

== Size of Structs

Structs have the size of their contained values.

[source,rust]
----
include::./2.rs[]
----

== References

References have the size of 1 `usize`. The same is true for simple boxes.

[source,rust]
----
include::./3.rs[]
----

== Trait Objects

Trait objects need 2 `usize`.

[source,rust]
----
include::./4.rs[]
----

== Slices

Slices need 2 usize. The same is true for their boxes.

<pre><code data-source="chapters/shared/code/memory-considerations/5.output" data-trim="hljs output" class="lang-rust"></code></pre>

== Vectors

Vectors need 3 usize, to additionally store their capacity.

<pre><code data-source="chapters/shared/code/memory-considerations/6.output" data-trim="hljs output" class="lang-rust"></code></pre>

== `&str`, `Box<str>`, `String`

They behave the same as slices and vectors.

== Enums

Enums need the size of their largest value, 1 byte for a discriminant, plus padding.

[source,rust]
----
include::./7.rs[]
----

---

If 0 is not a legal value, Option uses this as a the `None`-Case.

There is currently no stable way to communicate this to the compiler.

