:ferrous: https://ferrous-systems.com/[Ferrous Systems]

# Ferrous Teaching Material

This is free workshop material produced by {ferrous} for trainings.
mailto:contact@ferrous-systems.com[Get in touch] for a custom quote.
The time for the full course is around three to four days.

The material is created with people with zero Rust experience but with a programming background in mind.

Ferrous Systems offers a large Rust curriculum for both beginner and
advanced Rust developers. We are the oldest and most often
chosen Rust training provider.

Ferrous Systems specialises in custom, topic focused workshops for
enterprises starting moving into Rust. Supplemental to our courses, we
offer ongoing help and feedback.

Overview
--------

The materials are presented as a set of small, self-contained lessons on a specific topic.
Note that lessons might be taken down when deemed outdated and recreated for new audiences.
Lessons can be arranged into courses exploring various aspects of Rust.

Pricing
~~~~~~~

Ferrous Systems usually charges per trainer day. That allows for easy
calculation on one-off trainings and a fair and easy discussion about
the structure of the course. Other agreements are possible. For example,
that allows clients to quickly change the setup of the group, e.g. by
adding a person, without changing the contractual setup.

We offer training on any Rust subject and will create material that we
deem resuable at no cost for the client.

We also offer training directly on clients products, against a fee to
produce the material.

Group setup
~~~~~~~~~~~

Mixed backgrounds allow facilitating discussions within a group about
approaches and techniques. A similar experience level allows the trainer
to form better assumptions about what is already understood and what
not.

Ferrous Systems recommends a trainer per 6 attendees for full trainer
bandwidth. If possible, we recommend opting for groups of at least 12,
to efficiently allow for 2 trainers.

We have experiences with both groups of mixed and uniform backgrounds
and mixed skill levels. We generally recommend groups of mixed
backgrounds and similar experience levels.

Training material
~~~~~~~~~~~~~~~~~

Ferrous Systems offers their training material under MIT/Apache-2.0
license for source code and Creative Commons (CC-BY-SA) for textual
content.

Course material specifically constructed for you will be proprietary to
you.

Trainer staff
~~~~~~~~~~~~~

The Ferrous Systems trainer staff consists of multiple Rust project
maintainers and domain experts, active in multiple working groups. This
makes sure our trainers are always up to speed on new developments and
can give current and authoritive answers.

Among those are:

* Florian Gilcher: Training Rust since 2015. Over 30 trainings, most for
large enterprises. Rust core team member and community team manager.
Broad knowledge about all aspects of Rust, with special knowledge on
network and async/concurrent programming.
* James Munns: Training Rust since 2018. Focus on general Rust and
small/embedded systems. Member of the Embedded Working Group Core Team.
Great knowledge of integrating Rust with C codebases.
* Aleksey Kladov: Training Rust since 2018 in academic and enterprise
setting. Member of the Rust tools team. Author of the rust-analyzer IDE.
Very broad and exact knowledge of the language and its tooling,
especially focused on debugging.
* Jonas Schievek: Training Rust since 2019. Focus on general Rust and
multiple architectures. Contributor to the Rust compiler. Great
knowledge of compilation details and performance concerns.
* Tanks Transfeld: Training Rust since 2018. Focus on general Rust and
Rust for beginners. Part of several Rust learning projects. All Rust
subjects, from async to bare metal. Great knowledge around beginners
concerns and how to get started.

Ferrous Systems can also collaborate with local trainers in Europe, US,
South America and South Africa.

Courses
-------

Tailoring
~~~~~~~~~

Ferrous Systems offers courses in many different settings.

Courses will be tailored to the clients needs during an interview before
the event. This interview should happen as early as possible.

Specifically courses for companies in a transformation towards using
Rust will be tailored to the companies core subjects.

The ``three days'' core
~~~~~~~~~~~~~~~~~~~~~~~

Ferrous Systems builds its core course around a _base course_ of three
days. This course consists of introduction into shared Rust subjects
plus application in _one_ domain. Three days gives enough time to focus
on this domain for at least one day, plus enough time to answer
questions coming up from the audience.

After a three days course, attendees will have a solid knowledge in
Rusts core concepts, especially Ownership and Borrowing. They will also
have the core skills necessary for efficient self-guided learning.

Variations
^^^^^^^^^^

Variations of the course, such as a shorter or a longer version are
available.

``Three days'' overview
+++++++++++++++++++++++

A course that focuses more on an ecosystem overview over a detailed core
subject. It may cover up to 4 topics.

Attendees may not become productive in all areas, but get a good feeling
for them.

This course is perfect for engineering management, that will most likely
not end up using Rust daily, but needs broad knowledge to assess Rust as
a technology. It is also frequently given in academic settings.

5 days
^^^^^^

The longer versions covers similar subjects as above, but in more
detail. This allows e.g. the construction of a larger piece of software
in the training group collaboratively.

These courses are recommended for people that are intended to be
multipliers in your organisation.

After 5 days, attendees will have solid knowledge in a topical domain
and full productivity.

2 days
^^^^^^

A condensed version of the three days course. Detailed topic deep dives
will be reduced and some self-guided exercises reduced to ``code along''
sessions.

2,4 and 8 hours topic tasters
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Taster sessions that favor experiences over solid knowledge and get
people excited.

Perfect for conferences and internal all-hands to expand peoples
horizons.

Advanced courses
~~~~~~~~~~~~~~~~

Advanced courses deepen a Rust subject and are indended for groups that
already visited a course before. They quickly refreshen core knowledge
and then add a topical deep dive on topic. Advanced courses also differ
from base courses in that they include a number facilitated discussions
for attendees to share their experience.

Advanced courses are tailored like base courses to the need of the
group. For example, an basic course for for asynchronous programming
explains how concurrent execution in Rust works, the advanced one may
include writing your own execution engine.

Topics
------

Ferrous Systems offers Rust courses for a wide variety of subjects. The
following is a non-exhaustive list of subjects.

Every subject with be taught with hands-on exercises.

Core topics
~~~~~~~~~~~

This is the core component of the course. In this course, attendees will
learn:

* Ownership
* Borrowing
* Lifetimes
* Working with memory and data structures
* Control flow
* Structuring of applications
* Using and configuring cargo and rustup
* Introducing Rust into existing products
* General Rust patterns
* Error Handling
* Using Generic APIs
* Using Rusts guarantees for security gains
* Testing and Debugging
* Documentation tooling
* Basics of concurrency safety
* Overview of important documentation
* Overview the standard library, especially core interface like
collections, input/output and networking
* Overview of common libraries
* ``Refactoring towards Speed'': a core technique to safely derive a
fast program from a working program

Exercises will be tailored to the chosen special subjects.

Advanced Generic Programming in Rust
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Using libraries with generics in Rust is taught in the core course. When
to use them, and how is a big question in library development, though.

In this module, attendees will learn:

* Introduction into advanced programming with generics in Rust
* Writing generic APIs
* Impact on compile time, size and runtime speed
* Useful generics patterns
* Patterns to avoid

Rust in C/C++ Environments
~~~~~~~~~~~~~~~~~~~~~~~~~~

Rust is often deployed in existing products, especially withing or among
solutions written in C/C++. This module explains binding efficiently
from C/C++ to Rust and from Rust to C/C++ codebases.

In this module, attendees will learn:

* Rusts FFI (Foreign Function Interface)
* `unsafe`, as needed for FFI
* Safe binding, both manually and automatically
* Binding strategies
* Working with raw pointers and helping pointers
* Costs of boundary crossing
* Assessment of feasibility

Unsafe Rust
~~~~~~~~~~~

Rusts `unsafe` feature is sometimes necessary for speed optimisations or
implementation of special data structures. This module explains its
position and use in the language.

In this module, attendees will learn:

* The role of `unsafe`
* The scope of `unsafe`
* Do’s and Don’ts of unsafe Rust
* Introduction into support APIs, like non-null pointers
* Potential undefined behaviour arising from the use of `unsafe`
* Checking unsafe Rust vor safety

Rust Testing
~~~~~~~~~~~~

This module teaches advanced Rust testing techniques.

In this module, attendees will learn: * Fuzzing of Rust applications *
Using property based testing * Rust in continous integration *
Documentation testing

Rust for Application Development
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This module is meant for developers that mostly produce application
layer code and work less on libraries. It focuses less on line-by-line
details, but on system construction and usage of foreign code.

In this module, attendees will learn:

* Useful libraries for many common usecases
* How to evaluate a library
* Componentising Rust projects
* Error handling at large
* Logging and tracing

Binary Size Optimisation
~~~~~~~~~~~~~~~~~~~~~~~~

This module is meant for developers working on systems with constraints
on program size, such as switches or IoT gateways. It explains
techniques to keep the binary size of Rust applications small.

In this module, attendees will learn:

* Compiler options to optimise for size over aggressive optimisation
* Programming techniques for smaller programs
* Tools to further reduce the size of resulting binaries

Rust Speed Optimisation
~~~~~~~~~~~~~~~~~~~~~~~

This module is meant for developers working on systems with high speed
demands. It explains techniques to test for performance and optimise for
speed.

In this module, attendees will learn:

* Tools to analyse speed and memory consumption
* Programming techniques for faster programs
* ``Refactoring towards Speed'': futher deepening for optimising working
code bases
* Optimising programs for better resource usage

Rust for Networking
~~~~~~~~~~~~~~~~~~~

This module is meant for developers working on the networking layer. It
combines well with the ``Asynchronous and Concurrent Rust'' module.

In this module, attendees will learn:

* Rusts concurrency safety features
* The Futures model
* Rust async/.await programming
* Available libraries and frameworks
* Specifics of Rusts I/O libraries

Asynchronous and Concurrent Rust
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This module is meant for developers interested in building highly
concurrent systems. It combines well with the ``Rust for Networking''
module.

In this module, attendees will learn:

* Rust threads vs. asynchronous tasks
* Communication and sharing between concurrent units of a program
* Effective memory safety features in concurrent applications
* Available libraries and frameworks

Cross Compilation
~~~~~~~~~~~~~~~~~

This module is meant for developers targeting many different
architectures.

In this module, attendees will learn:

* Rusts cross-compile toolchain
* Dealing with target differences
* Keeping programs portable
* Configuring targets in cargo
* (optional) Defining your own custom targets
* (optional) cross-compiling mixed codebases

The optional targets are taught on client need.

Embedded Rust
~~~~~~~~~~~~~

This module is meant for developers interested in building bare metal
systems such as microcontrollers. It includes the ``Cross-Compilation''
module, as far as it applies to microcontrollers.

In this module, attendees will learn:

* Cross-compilation of Rust to embedded devices
* Programming Rust without a standard library
* Target specific libraries for microcontrollers
* Rust embedded hardware abstraction layer (``embedded HAL'')
* Libraries for use in heapless environments
* Managing memory mapped devices

Embedded Rust using RTFM
~~~~~~~~~~~~~~~~~~~~~~~~

This module is similar to ``Embedded Rust'', but uses the
https://rtfm.rs[``Real Time For The Masses''] concurrency framework for
teaching.

Writing Drivers for Embedded Rust
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This module extends the ``Embedded Rust'' or ``Embedded Rust using
RTFM'' module.

In this module, attendees will learn:

* How to build a driver
* Proper modularisation
* Testing

Productive coding in Rust
~~~~~~~~~~~~~~~~~~~~~~~~~

This module further teaches Rust techniques, also with the support of
IDEs.

In this module, attendees will learn:

* Setting up rust-analyzer or CLion to their needs
* General development workflows
** Draft coding
** Going from draft to stable software
** ``Refactoring towards speed''
* Fast testing
* Tools for reactive development workflows (such as `cargo watch`)

Rust and WebAssembly (WASM)
~~~~~~~~~~~~~~~~~~~~~~~~~~~

WebAssembly (WASM) is a intermediate language optimised for fast
evaluation in secure sandboxes. This module focuses on understanding the
role of WebAssembly and its usage. It is taught on a platform relevant
to the group.

In this module, attendees will learn:

* What WASM is and what to use it for
* Security properties of WASM and WASI
* Common WASM implementations
* Binding between a host language (usually JavaScript) and WASM

## Credits

The development of this course is financed by {ferrous}.

They are open sourced as a contribution to the growth of the Rust language.

If you want to fund further development of the course, book a training!

## Commercial use

This course is expressively intended for commercial and free use.

## License

https://creativecommons.org/licenses/by-sa/4.0/
