= The Toolchain

link:./index.html[Table of Contents]

== Rustup

Rustup installs and manages Rust compiler toolchains

https://rust-lang.org/tools/install

*It is not the Rust compiler!*

== Important commands

[source,sh]
----
include::./1.sh[]
----

For up-to-date information, please see link:https://rust-lang.github.io/rustup-components-history/[Rust Component History]

== Contents of the toolchain

- rustc, rust-docs, rust-std, rustfmt, rust-(lldb|gdb)^*^
- cargo, cargo-fmt
- clippy
- libcore/libstd

^*^ The debugger installed is platform dependent.

== rustc

[source,sh]
----
include::./3.sh[]
----

The Rust compiler builds and links Rust code.

== The quintessential beginning

[source,rust]
----
include::./4.rs[]
----

== The quintessential output

[source,sh]
----
include::./5b.sh[]
----

== Cargo

[source,sh]
----
include::./6.sh[]
----

== Cargo contd.

Cargo is Rusts build and package management tool.

Cargo is installed along with `rustc`, but is not tightly coupled to a `rustc` version.

== Once more with Cargo

[source,sh]
----
include::./7.sh[]
----

== A Little Look Around

- What is in Cargo.toml?
- What is in Cargo.lock?

For details, check the http://doc.crates.io/manifest.html[Cargo Manifest docs].

== Playground

* Playground: https://play.rust-lang.org

== IDEs

* rust-analyzer: https://rust-analyzer.github.io
* IntelliJ Rust plugin for their IDEs (CLion, Idea, etc.): https://www.jetbrains.com/rust/

== Add some tooling

[source,sh]
----
include::./8.sh[]
----
