= Error Handling

link:./index.html[Table of Contents]


== !

Error handling is explicit in Rust.

Any function with known error conditions returns a `Result<T,E>`.

**There are no exceptions.**

== !

[source,rust]
----
include::./1.rs[]
----

== Results Must Be Used

[source]
----
include::./6.output[]
----

== Using Results With `match`

[source,rust]
----
include::./3.rs[]
----

== Using Results With Conditionals

Check for success with `is_ok()`, errors with `is_err()`:

[source,rust]
----
include::./4.rs[]
----

== Using Results With `?`

Use `?` in functions with multiple possible failures.

[source,rust]
----
include::./5.rs[]
----

== Using Results With `?`

Output:

[source,rust]
----
include::./6.output[]
----

Note the early exit.

== Using `?` in `main`

* `main` can return `Result`

[source,rust]
----
include::./6.rs[]
----

== Mapping Result Values

[source,rust]
----
include::./7.rs[]
----
`map_err()` is also available.

== Dynamic errors

Rust has a an idiomatic dynamic error type, which most errors can be converted into:

[source,rust]
----
include::./8.rs[]
----

To be converted like this, errors must implement the std::error::Error trait.

== Reporting Errors Only

If you only have to report an error, but don't have a meaningful return value, use `Result<(), Error>`.

