= Error Handling
:revealjs_width: 1920
:revealjs_height: 1080
:source-highlighter: highlightjs

link:./index.html[Table of Contents]


== !

Error handling is explicit in Rust.

Any function with known error conditions returns a `Result<T,E>`.

**There are no exceptions.**

== !

[source,rust]
----
include::./1.rs[]
----

== Results Must Be Used

<pre><code data-source="chapters/shared/code/error-handling/2.output" data-trim="hljs output"></code></pre>

== Using Results With `match`

[source,rust]
----
include::./3.rs[]
----

== Using Results With Conditionals

Check for success with `is_ok()`, errors with `is_err()`:

[source,rust]
----
include::./4.rs[]
----

== Using Results With `?`

Use `?` in functions with multiple possible failures.

[source,rust]
----
include::./5.rs[]
----

== Using Results With `?`

Output:

<pre><code data-source="chapters/shared/code/error-handling/6.output" data-trim="hljs output"></code></pre>
Note the early exit.

== Using `?` in `main`

* `main` can return `Result`
* Stable in Rust since `1.26`.

[source,rust]
----
include::./6.rs[]
----

== Results Are Wrapper Types

It's possible to change a `Result<T,E>` into a `Result<U,E>` without unwrapping it.

Transforming a `Result<T,E>` into a `Result<T,X>` is also possible.

[source]
----
include::./1.diagram[]
----

== Mapping Result Values

[source,rust]
----
include::./7.rs[]
----
`map_err()` is also available.

== Reporting Errors Only

If you only have to report an error, but don't have a meaningful return value, use `Result<(), Error>`.
