= Imports, Modules and Visibility

link:./index.html[Table of Contents]


== Imports

All used items must be declared. This is similar to Java or Haskell.

[source,rust]
----
include::./1.rs[]
----

== Module Imports

It is possible to import the module instead and qualify every use.

[source,rust]
----
include::./2.rs[]
----

== Glob Imports

You can also import everything from a module.

[source,rust]
----
include::./3.rs[]
----

This is *generally* frowned upon.

== Prelude

One exception to the rule is the "Prelude": This is a special module in the standard library that is automatically fully imported.

== Other Preludes

Other libraries offer `prelude`-Modules, one of the most common is `std::io`.

[source,rust]
----
include::./4.rs[]
----

Here, the glob is accepted.

== Structured imports

You can combine multiple things, that are also nested.

[source,rust]
----
include::./4-5.rs[]
----

== Renaming on import

[source,rust]
----
include::./5.rs[]
----

== Local import

Imports can happen inside a function. They only take effect within the function.

[source,rust]
----
include::./6.rs[]
----

== Modules

The module system of Rust is similar to Python.

== !

-   every source file is a module
-   submodules can be in the same file or in another
-   libraries are called "crates" and contain modules

== !

By convention, the root module of a library is found in `src/lib.rs`.

the root module of a single application in `src/main.rs`.

The root modules for multiple applications in `src/bin/*.rs`.

== Example

[source,rust]
----
include::./7.rs[]
----

== Moving the Module to a Separate File

Our application could also have the following layout:

[source,rust]
----
include::./8.rs[]
----

== A Larger Module as a Directory

Simply by adding a new folder of the same name

[source,rust]
----
include::./9-2.rs[]
----

== A Larger Module as a Directory

Or declare a module via `mod.rs`

[source,rust]
----
include::./9.rs[]
----

== !

In both cases, the module must be registered with the root module.

[source,rust]
----
include::./10.rs[]
----

== !

With the last approach, you can create additional modules relative to `mod.rs`.

== Visibility

In Rust, everything is private by default. Publicly available types are marked with `pub`.

Public types and functions that can be reached through a public module path are exported.

== Example

[source,rust]
----
include::./11.rs[]
----

== !

Traits must be public and imported before use.

The compiler will detect if you use an un-imported trait.

== Structs

Struct fields are not exported (public) by default.
A struct with non-public members can't be constructed or fully used outside of its module. This is often intended.

Struct functions are also not exported by default.

== !

[source,rust]
----
include::./12.rs[]
----

== !

[source,rust]
----
include::./13.rs[]
----

== !

In general, exporting fields should be avoided:

* Any change of the structure leads to API breakage

* Accessor functions are usually as fast as direct field access due to optimizations.

== Pub qualifiers

[source,rust]
----
include::./14.rs[]
----
