= Implementation and Traits

link:./index.html[Table of Contents]

== !

Rust offers the possibility to bind functions to types.

== Warning

== !

This sometimes looks like object-oriented programming, but it is not.

In particular, run-time polymorphism, messages, classes, subtypes, and method overload are missing.

== Simple implementations: associated function

[source,rust]
----
include::./1.rs[]
----

== Remark

`new` here is purely convention.

== A Python analogy

[.notes]
--
- if you're familiar with Python's `self`, Rust's use of it is very very similar
--


[source,rust]
----
include::./2.rs[]
----

== Borrowing and Ownership of `self`

It is like normal ownership and borrowing, but at the beginning somewhat unfamiliar.

-   Borrowing through one function *simultaneously borrows self*.
-   This is especially applicable for mutable borrows!
-   `self` without `&` takes ownership to the value from the calling context.

== Borrowing and Ownership of `self`
|===
|Owned |Borrowed |Mutably borrowed

|self
|&self
|&mut self

|===



== Interesting Differences to Common OO

-   Values can be replaced when calling `&mut` functions
-   Values, for example iterators and builders, can have methods that consume `self` and are thus invalidated.
-   This solves the problem of invalidating iterators!

== Side note

-   Implementations can occur multiple times. This is useful when multiple constraints are needed.

== Traits

Traits are Rust's particular way of abstracting over types.

== !

We've already met a trait: `Debug`.

== !

Traits define functions types must implement. They can then be used generically.

== !

[source,rust]
----
include::./4.rs[]
----

== Self

`Self` is a special type: it is the type currently being implemented.

== Generic Traits

Traits can have type parameters.

== !

[source,rust]
----
include::./5.rs[]
----

== !

Working with generic traits is very common.

== Inference of Traits

Type inference of traits is very advanced, but sometimes, undecidable situations can occur. In this case, the compiler needs help deciding.

There are multiple techniques.

== Full qualified function calls

[source,rust]
----
include::./6.rs[]
----

Any reachable function in Rust can be addressed with this syntax.

== Associated Types

Associated types are generic parameters, but they are ignored during inference.

== !

[source,rust]
----
include::./7.rs[]
----

== `impl Trait`

`impl Trait` is used when the type of a value does not need to be named.

[source,rust]
----
fn main() {
    let v = vec![1,2,3];
    let i = make_iter(&v);
}

fn make_iter<'a>(v: &'a Vec<u8>) -> impl Iterator<Item=u8> + 'a {
    v.iter().map(|v| (*v)*2)
}
----


== !

[source,rust]
----
fn main() {
    let v = vec![1,2,3];
    let i = v.iter();
    let i2 = double(i);
}

fn double<'a>(i: impl Iterator<Item=&'a u8> + 'a) -> impl Iterator<Item=u8> + 'a {
    i.map(|v| (*v)*2)
}
----
== !

Limitations:

* No `impl Trait` in trait methods

== !

[source,rust]
----
trait Foo {}

trait Bar {
    fn fooify(&self) -> impl Foo;
}
----
