= Implementation and Traits

link:./index.html[Table of Contents]


== !

Rust offers the possibility to bind functions to types.

== !

# Warning

This sometimes looks like object-oriented programming, but it is not.

In particular, run-time polymorphism, messages, classes, subtypes, and method overload are missing.

== Simple implementations: associated function

[source,rust]
----
include::./1.rs[]
----

== Remark

`new` here is purely convention.

== Python Says Hello

[source,rust]
----
include::./2.rs[]
----

== Borrowing and Ownership of `self`

It is not unlike normal, but at the beginning somewhat unfamiliar.

-   Borrowing through one function *simultaneously borrows self*.
-   This is especially applicable for mutable borrows!
-   `self` without `&` returns ownership to the value from the calling context.

== Interesting Differences to Common OO

-   Values can replace themselves
-   Values, for example, iterators and builders can have methods that consume `self` and are thus invalidated.
-   This solves the problem of invalidating iterators.

== Sidenote

-   Implementations can occur multiple times

== Self

`Self` is a special type in Rust. It always references the type to which the implementation refers.

[source,rust]
----
include::./3.rs[]
----

== Traits

Traits are Rusts variant of abstracting over types.

== !

We've already met a trait: `Debug`.

== !

Traits define functions types must implement. They can then be used generically.

== !

[source,rust]
----
include::./4.rs[]
----

== Self

`Self` is a special type: it is the type currently being implemented.

== Generic Traits

Traits can have type parameters.

== !

[source,rust]
----
include::./5.rs[]
----

== !

Working with generic traits is very usual.

== Inference of Traits

Type inference of traits is very advanced, but sometimes, undecidable situations can occur. In this case, the compiler needs help deciding.

There are multiple techniques.

== UFCS

Unified Function Call Syntax

[source,rust]
----
include::./6.rs[]
----

== Associated Types

Associated types are generic parameters, but they are ignored during inference.

== !

[source,rust]
----
include::./7.rs[]
----

== `impl Trait`

`impl Trait` is used when the type of a value does not need to be named.

```rust
fn main() {
    let v = vec![1,2,3];
    let i = make_iter(&v);
}

fn make_iter<'a>(v: &'a Vec<u8>) -> impl Iterator<Item=u8> + 'a {
    v.iter().map(|v| (*v)*2)
}
```

== !

```rust
fn main() {
    let v = vec![1,2,3];
    let i = v.iter();
    let i2 = double(i);
}

fn double<'a>(i: impl Iterator<Item=&'a u8> + 'a) -> impl Iterator<Item=u8> + 'a {
    i.map(|v| (*v)*2)
}
```

== !

Limitations:
* No `impl Trait` in trait methods

== !

```rust
trait Foo {}

trait Bar {
    fn fooify(&self) -> impl Foo;
}
```
