= Ownership

link:./index.html[Table of Contents]

== !

Ownership is the basis for the memory management of Rust.

== Rules

-   Every value has exactly one owner
-   Ownership can be passed on
-   The owner is responsible for removing the data from memory
-   The owner has all powers over the data and can mutate it


== !

These rules:

-   are fundamental to Rusts type system
-   are enforced at compile time
-   are practical in many other ways

== Example

[source,rust]
----
include::./1.rs[]
----

== !

[source]
----
include::./1.diagram[]
----

== !

What happens if we try to use `dot` a second time?

== !

[source,rust]
----
include::./2.rs[]
----

== Oops!

== !

In Rust-Lingo, this is called `consuming`. `pacman` consumes `dot`.

The value cannot be used anymore.

== Background

When calling `pacman` with `dot`, the value is "moved" into the arguments of `pacman`. At that moment, ownership passes to `pacman`. `main` is not owner of the data anymore and thus not allowed to access or manipulate them.

== Working with moves: explicit clone

What, if that behaviour is unwanted? We can create a second copy of the data!

== !

[source,rust]
----
include::./3.rs[]
----

== !

[source]
----
include::./2.diagram[]
----

== !

Cloning is a general operation that - depending on the complexity of the data at hand - can be costly.

== Working with moves: copy instead of move

[source,rust]
----
include::./4.rs[]
----

== !

Copy is meant for data that can be quickly copied in memory (using memcopy) and are allowed to be copied (e.g.: not File pointers).


== !

Values that are copy follow the standard ownership rules, but they are copied when ownership is passed on.

== Warning

== !

The terminology around moves is similar, but not the same to the one used in C++, which is why you should always use Rust-Terminology: Ownership, passing on ownership and consumption.

== Practical example

[source,rust]
----
include::./5.rs[]
----

What would happen if we use could use File after calling `use_file`?

== Small quiz

`drop` is the function that deallocates a value immediately. What does the implementation look like?

[source,rust]
----
include::./6.rs[]
----

== !

[source,rust]
----
include::./7.rs[]
----
