= Lifetimes

link:./index.html[Table of Contents]


== !

[source,rust]
----
include::./1.rs[]
----

== !

[source,rust]
----
include::./2.rs[]
----

== !

Rusts lifetimes are notorious for being hard to understand.

== !

That is not necessary.

== Lifetimes

-   Lifetimes describe the time that values remain in memory
-   They describe - they cannot force or change anything
-   Lifetimes are types!

== You have used them already

[source,rust]
----
include::./3.rs[]
----

== Motivation

[source,rust]
----
include::./4.rs[]
----

== !

This code would - if it compiled - violate memory safety.

== !

The correct struct definition is:

[source,rust]
----
include::./5.rs[]
----

== !

Wrapper is now:

* Generic over the type T
* As well as a lifetime 'a (its own)
* The borrowed values must live *at least equally long*

== !

Takeaway:

Lifetimes describe minimal conditions

== Multiple lifetimes in one signature

[source,rust]
----
include::./6.rs[]
----

== Sublifetimes

[source,rust]
----
include::./7.rs[]
----

== !

Lingo: `Input outlives Tokenizer`

== !

Lifetimes cannot do _more_ than describe "this must live longer (or at least equally long) as the other".

== !

Common pitfall: you cannot "shorten a lifetime", as it just describes what's already there.

== `'static`

`'static` is a lifetime that lives longer than all others. That's not necessarily forever!

== !

Examples of `'static` data are:

* Data contained in the binary, for example static strings
* Heap-allocated values (for example the contents of a `Box`)
    - As long as they are not bound on values that live shorter!
* Globals

== !

`'static` is not an escape hatch. In concurrent, especially evented, programs, `'static` is very common.

This is due to most data having to live outside of the stack.

== !

Lifetimes describe all types, not only references, therefore they are also bounds in generic code.

[source,rust]
----
include::./8.rs[]
----

== Lifetime-Elision

For simple cases, lifetimes are automatically inserted into signatures.

[source,rust]
----
include::./9.rs[]
----

== Lifetimes and Bindings

[source,rust]
----
include::./10.rs[]
----
[source,rust]
----
include::./11.rs[]
----

== Lifetimes and Boxes

For boxes, the default lifetime bound of the contained value is `'static`. Sometimes, this is too long and can be overwritten:

<pre><code data-source="chapters/shared/code/lifetimes/12.rs" data-trim="hljs rust" class="lang-rust" class="lang-rust"></code></pre>
