= Exercise: Actix & Websockets
:source-language:  rust

In this exercise you will learn how to

* use a web server with link:https://github.com/actix/actix[actix] & Actors
* use link:https://github.com/actix/actix-web/tree/master/actix-web-actors[websockets] to communicate messages between frontend and web server
* use the link:https://docs.rs/env_logger/0.9.0/env_logger/[`env_logger`] crate
* implement custom message handler(s)

The web server runs at http://localhost:8080. Once started, open the link in a browser. The rudimentary UI allows you to connect to the web server, meaning you will join the chat server. Once connected you can write messages in the text input field. Received messages will be displayed in the text box.


== Tasks

1. Broadcast the client message to all other connected clients
2. Implement a custom message to disconnect from the chat server
  - you should not receive new messages from other clients thereafter
3. Check that you do not receive your own chat message back
4. Add heartbeat logic to remove a client from the chat server after 10s of inactivity (e.g. tab closed)
  - use link:https://docs.rs/actix/0.10.0/actix/trait.AsyncContext.html#method.run_interval[`actix::AsyncContext::run_interval`] to run the 

== Getting Started

Clone the repository at link:https://github.com/ferrous-systems/teaching-material[ferrous-systems/teaching-material]. You find the assignment in folder `assignments/actix/chat-websockets`.

Run the web server with `cargo run` to start the chat server.

CAUTION: The given dependencies of the `Cargo.toml` are not the most recent versions due to some incompatibilities. Updating these may not compile the program anymore.

== Help

* link:https://docs.rs/actix-web-actors/3.0.0/actix_web_actors/[actix-web-actors] API documentation, check `Message` enum
* link:https://docs.rs/actix/0.10.0/actix/trait.AsyncContext.html#method.run_interval[actix::ASyncContext] documentation


== Bonus Tasks

1. Add support to send the name initially
  - For this you need to adapt `index.html` page, remove the `visibility:hidden;` style from the `name` input field
  - Think about how to distinguish setting the name from sending a text, e.g. using a prefix, then send the name
  - Expand the `WsChatSession` struct to store the name, adapt code accordingly
  - If name is available output it instead of displaying `Someone` in code
