= Exercise: Bulls and Cows
:source-language: rust

In this exercise, you will learn

* How to work with rust slices and vectors.
* How to accept input from stdin.

In this assignment we will implement the game "Bulls and Cows".

The game creates a random secret with four random numbers from one to four.

For example:

```
secret: 3 3 1 2
```

We try to guess the secret but are given only the numbers of "Bulls" and "Cows".

* Bulls are guesses in the exact place.
* Cows are guesses in the wrong place.

Values are counted exactly once in the guess and the secret.

The task is to implement this function:

```
fn num_bulls_and_cows(guess: &[i32], secret: &[i32]) -> (i32, i32) {
    ...
}
```

This returns `(Bulls, Cows)`.

Here is a test to help you:

```
#[test]
fn test_num_bulls_and_cows() {
    assert_eq!(num_bulls_and_cows(&[1, 2, 3, 4], &[1, 2, 3, 4]), (4, 0));
    assert_eq!(num_bulls_and_cows(&[1, 2, 3, 5], &[1, 2, 3, 4]), (3, 0));
    assert_eq!(num_bulls_and_cows(&[4, 3, 2, 1], &[1, 2, 3, 4]), (0, 4));
    assert_eq!(num_bulls_and_cows(&[1, 2, 3, 1], &[1, 2, 3, 4]), (3, 0));
    assert_eq!(num_bulls_and_cows(&[1, 1, 1, 1], &[1, 2, 3, 4]), (1, 0));
    assert_eq!(num_bulls_and_cows(&[1, 2, 2, 2], &[2, 2, 2, 1]), (2, 2));
    assert_eq!(num_bulls_and_cows(&[1, 3, 3, 2], &[2, 2, 2, 1]), (0, 2));
}
```

== Step 1.

You can use the "rand" crate to generate guesses.

```
    let secret : Vec<_> = (0..NUM_DIGITS).map(|_| ??? ).collect();
```

== Step 2.

Parse an input string.

```
    let stdin = std::io::stdin();

    let mut buf = String::new();

    loop {
        buf.clear();
        eprint!("guess: ");
        stdin.read_line(&mut buf).unwrap();
        let guess : Result<Vec<i32>, _> = buf.trim().split(' ').map(|s| s.parse()).collect();
    }
```

== Step 3.

If the guess is correctly formed, count the number of bulls and cows.

```
                let (bulls, cows) = num_bulls_and_cows(&guess, &secret);

                eprintln!("{:?} has {} bulls and {} cows", guess, bulls, cows);
```

== Step 4.

Write the bulls and cows function.

Hint:

Check the bulls first and then tick them off by removing them from the guess and secret.
Then check the cows. This way you don't count anything twice.

Make sure all the tests pass.

== Step 5.

Play the game.
