= Exercise: FizzBuzz
:icons: font
:source-highlighter: pygments
:pygments-style: borland

:source-language: rust

In this exercise, we will implement our first tiny program: FizzBuzz. FizzBuzz is easy to implement, but allows for application of Rust patterns in a very clean fasion.

You will learn:

* How to write a simple Rust program
* How to create and return owned `String`s
* How to use conditionals
* How to format strings with and without printing them to the system console

== Task

1. Use Cargo to create a new project called `fizzbuzz`
2. Implement the following function:
+
[source,rust]
----
fn fizzbuzz(i: u32) -> String {
    ///....
}
----
+
Implementing the following rules:

  * If `i` is divisible by `3`, return `String::new("Fizz")`
  * If `i` is divisible by `5`, return `String::new("Buzz")`
  * If `i` is divisible by both `3` and `5`, return `String::new("FizzBuzz")`
  * Return the number as a String, otherwise, using `format!("{}", i)`

3. Write a main function that prints the values from `1` to `100`

== Help

This section gives partial solutions to look at or refer to.

In general, we also recommend to use the Rust documentation to figure out things you are missing to familiarise yourself with it. If you ever feel completely stuck or that you haven't understood something, please hail the trainers quickly.

=== Getting Started

Create a new binary Cargo project, check the build and see if it runs:

[source]
----
$ cargo new fizzbuzz
$ cd fizzbuzz
$ cargo run
----

=== Creating Strings

The recommended ways to get a `String` type for this exercise are:

[source,rust]
----
let string = String::from("Fizz");
let i = 4;
let string = format!("{}", i);
----

=== Counting from 1 to 100

If you have issues that your program only counts to 99, be aware that the `..`-range syntax in Rust is _end-exclusive_. Either move the bound or use the inclusive range syntax.

[source,rust]
----
for i in 1..100 { // counts to 99

}

for i in 1..101 { // counts to 100

}

for i in 1..=100 { // counts including 100

}
----

=== Returning data

If you have issues returning data from multiple branches of your solution, liberally use `return`.

[source,rust]
----
if x % 5 == 0 {
    return String::from("Buzz");
}
----

=== Printing to console

The recommended way to print to the console in this exercise is `println!`. `println!` _always_ needs a format string.

[source,rust]
----
let s = String::from("Fizz");
println!("{}", s);
----


