= Setup of the toolchain

link:./index.html[Table of Contents]


== !

Overview

== Rustup

Rustup is the standard tool for managing Rusts compiler toolchain.

http://rustup.rs/

== Important Commands

[source,sh]
----
include::./01_important_commands.sh[]
----

== First Steps

== !

Execute the following commands:

[source,sh]
----
include::./02_first_steps.sh[]
----

This loads the sources of the default library and documentation for completion and offline use.

== Functional Test

[source,rust]
----
include::./4.rs[]
----

== !

[source,sh]
----
include::./5a.sh[]
----

== !

declaring of variables, scope,

== !

* wasm-pack
+
[source,sh]
----
curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
----

* cargo-generate
+
[source,sh]
----
cargo install cargo-generate
----

* npm
+
[source,sh]
----
npm install npm@latest -g
----

== Clone the Project Template

[source,sh]
----
include::./03_clone_project_template.sh[]
----

New project name:

[source,sh]
----
include::./04_clone_project_template.sh[]
----

== What's inside?

[source,sh]
----
include::./05_root.sh[]
----

== Build the Project

[source,sh]
----
include::./06_wasm_pack_build.sh[]
----

* Ensures Rust 1.30 or newer and the wasm32-unknown-unknown target were installed via rustup
* Compiles Rust sources into a WebAssembly .wasm binary via cargo
* Use wasm-bindgen to generate the JavaScript API for using the Rust-generated WebAssembly


== !

What's inside pkg?

[source,sh]
----
include::./07_pkg.sh[]
----

== Putting it into a Web Page

[source,sh]
----
include::./08_npm_init_wasm.sh[]
----

== !

What's inside www?

[source,sh]
----
include::./09_www.sh[]
----

== !

Install dependencies

[source,rust]
----
include::./10_npm_install.sh[]
----

== !

Using Local wasm-game-of-life Package in www

[source,sh]
----
include::./11_npm_link.sh[]
----

[source,sh]
----
include::./12_npm_link.sh[]
----

== !

Modify index.js to import wasm-game-of-life instead of the hello-wasm-pack package:

[source,js]
----
include::./13_modify_index.js[]
----

== !

The Web page is now ready to be served locally!

[source,sh]
----
include::./14_npm_run_start.sh[]
----

Navigate your Web browser to http://localhost:8080/

== !

Picture?

== !

Rust Syntax on Example

[source,rust]
----
include::./00_syntax_on_example.rs[]
----

== !


Rebuild the `.wasm` binary with `wasm-pack build`, refresh http://localhost:8080/

[source,rust]
----
include::./00_syntax_on_example.rs[]
----

== !

Solution:

[source,rust]
----
include::./00_solution_lib.rs[]
----

[source,js]
----
include::./00_index_.js[]
----
