= Crates

link:./index.html[Table of Contents]

== !

Rust calls libraries `crates`. Management of crates is generally done through `cargo`, but this is not strictly necessary.

== Usage of libraries

In Rust 2015 you need to declare crates via the `extern crate`-statement.

[source,rust]
----
include::./0.rs[]
----

This imports the "SERialisation/DEserialisation"-Framework.

== !

In Rust 2018 this is no longer required.
Libraries that were declared via cargo can simply be used with `use`-statements.

[source,rust]
----
include::./1.rs[]
----

== Macro usage

Since Rust 2018 you no longer have to explicitly import macros, they work just like functions.

Simply call a macro as follows

[source,rust]
----
include::./2.rs[]
----

You might still encounter older Rust code which relies on `#[macro_use]`

== !

Crates can be renamed, just like normal use statements:

[source,rust]
----
include::./3.rs[]
----

Note the `crate` keyword before it's usage. You're using a local alias. The original still exists.

== !

Alternative: rename dependencies via cargo:

[source,toml]
----
include::./4.toml[]
----

== crates.io

Published crates can be found on https://crates.io[crates.io], their documentation is automatically published to https://docs.rs[docs.rs].

== Crates and Applications

`cargo install my_crate` installs the applications shipped with a crate.
