= Outlook

link:./index.html[Table of Contents]


== !

What is coming in the near future for Rust?

== Rust 2018

== !

At the end of 2018 the culmination of feature stabilization throughout the year was released as `Rust 2018`

== !

Languages change over time.

But stability and backwards compatibility are fundamental.

== !

Making core changes to the language without breaking *any* existing code.

Changes are opt-in.

<pre><code data-source="chapters/shared/code/outlook/1.toml" data-trim="hljs toml" class="lang-rust"></code></pre>

== Some of the changes

=== Module system rework

[source,rust]
----
include::./1.rs[]
----

[source,rust]
----
include::./2.rs[]
----

=== Path clarity

[source,rust]
----
include::./3.rs[]
----

=== No more `extern crate`

=== `?` in `main()`

[source,rust]
----
include::./4.rs[]
----

=== Loops can `break` a value

[source,rust]
----
include::./5.rs[]
----

=== `impl Trait` vs `dyn Trait`

Unamed types that implement a specific trait vs dynamic trait objects

[source,rust]
----
include::./6.rs[]
----

== !

`dyn Trait` is the new syntax for trait objects.

It turned out that the syntax `impl T` vs `T` was confusing and asymmetric.

[source,rust]
----
include::./7.rs[]
----

=== Many, many more things

Too many too list. Here's a short list

- x86 SIMD
- 128-bit primitives
- `_` anonymous lifetimes
- `async` & `await`
- Stable procedural macros (compiler attributes)
- `..=` for inclusive ranges
- ... etc ...
