= Send & Sync

link:./index.html[Table of Contents]


== !

There are two special traits in Rust for concurrency semantics.

-   `Send` marks a structure safe to *send* between threads.
-   `Sync` marks a structure safe to *share* between threads.
    -   (`&T` is `Send`)

== !

These traits are what Rust uses to prevent data races.

They are *automatically derived* for all types if appropriate.

== Automatically Derived

[source,rust]
----
include::./1.rs[]
----

== !

There are some notable types which are not `Send` or `Sync`.

Such as `Rc`, raw pointers, and `UnsafeCell`.

== Example: `Rc`

[source,rust]
----
include::./2.rs[]
----

== Example: `Rc`

[source,bash]
----
include::./3.output[]
----

== Implementing

It's possible to add the implementation of `Send` and `Sync` to a type.

[source,rust]
----
include::./4.rs[]
----
In these cases, the task of thread safety is left to the implementor.

== Relationships

If a type implements both `Sync` and `Copy` then it can also implement `Send`.

== Relationships

A type `&T` can implement `Send` if the type `T` also implements `Sync`.

[source,rust]
----
include::./5.rs[]
----

== Relationships

A type `&mut T` can implement `Send` if the type `T` also implements `Send`.

[source,rust]
----
include::./6.rs[]
----

== Consequences

What are the consequences of having `Send` and `Sync`?

== Consequences

Carrying this information at the type system level allows driving data race bugs down to a *compile time* level.

Preventing this error class from reaching production systems.

`Send` and `Sync` are independent of the choice of concurrency (async, threaded, etc.).
