= Ownership & Borrowing

[.notes]
--

- stress that this is central to understanding Rust and that we will spend as much time on it as needed until everyone feel like they have a grasp on it
--

link:./index.html[Table of Contents]

== !

Ownership is the basis for the memory management of Rust.

== Rules

[.notes]
--

- you can use the metaphor of a physical book: I own it, I can decide to mutate it (e.g. by coloring in it or not), I'm responsible for its whereabouts and disposal
--

-   Every value has exactly one owner
-   Ownership can be passed on, both to functions and other types
-   The owner is responsible for removing the data from memory
-   The owner has all powers over the data and can mutate it

== !

These rules:

-   are fundamental to Rust's type system
-   are enforced at compile time
-   are practical in many other ways

== Example

[source,rust]
----
include::./1.rs[]
----

<1> Tries to open a file
<2> Checks the Result of the opening operation
<3> Take ownership of the file handle
<4> Remove the handle and close it in the process

== Ownership passing

[source,rust]
----
include::./2.rs[]
----

<1> Ownership is passed here.
<2> The value dropped here.

== First safety checkpoint

[source,rust]
----
include::./3.rs[]
----

<1> This is illegal.

== Oops!

----
include::./3.error[]
----

== !

In Rust-Lingo, this is called `consuming`.

The value cannot be used anymore.

== Background

When calling `write_and_close` with `file`, the value is "moved" into the arguments of `write_and_close`.

At that moment, ownership passes to `write_and_close`.

`main` is not owner of the data anymore and thus not allowed to access or manipulate them.

== References & Borrowing

[.notes]
--

- book metaphor: I can mutably borrow my book to a friend to color in it read it, and then immutably borrow it to another to look at the pretty colors

--

Intuitively: what you own, you can borrow.

---

[source,rust]
----
include::./4.rs[]
----

== Immutable references

`&` is the so-called "immutable" reference. They are:

* Available multiple times
* Always valid (always pointing to living data)
* Never `null`
* Guaranteed to never observe mutation of the pointee

== Mutable Borrowing

[source,rust]
----
include::./5.rs[]
----

== Mutable references

[.notes]
--

- hot take: *shared* mutable data is the root of all evil.
  mutable data itself is ok, as long as you follow the ownership rules!
--

`&mut` is the so-called "mutable" reference. They are:

* Available only once at a time
* Always valid (always pointing to living data)
* Never `null`
* Guaranteed to never alias (no two references point to the same data)

[.centered]
== The Borrowing Rules

Values can be:

* Borrowed immutably as often as you'd like
* Or mutably exactly once at a time
* The two rules are mutually exclusive.

Rust forbids _shared mutability_.

== Types and their ownership behaviour

|===
|Owned |Borrowed |Mutably borrowed

|i32
|&i32
|&mut i32

|Point
|&Point
|&mut Point

|Box<i32>
|&i32
|&mut i32
|===

== Collections and their ownership behaviour

|===
|Owned |Borrowed |Mutably borrowed

|Vec<i32>
|&[i32]
|&mut [i32] or &mut Vec<i32>

|String
|&str
|&mut String and &mut str
|===


== Working with moves: explicit clone

What if ownership behaviour is getting messy, but we don't want to reference?

We can create a second copy of the data!

== !

[source,rust]
----
include::./6.rs[]
----

== !

Cloning is a general operation that - depending on the complexity of the data at hand - can be costly.

== Working with moves: copy instead of move

[source,rust]
----
include::./7.rs[]
----

== !

Copy is meant for data that can be quickly copied in memory (using memcopy) and are allowed to be copied (e.g.: not File pointers).


== !

Values that are copy follow the standard ownership rules, but they are copied when ownership is passed on.

== Warning

The terminology around moves is similar, but not the same to the one used in C++, which is why you should always use Rust-Terminology: Ownership, passing on ownership and consumption.


== Small quiz

`drop` is the function that deallocates a value immediately. What does the implementation look like?

[source,rust]
----
include::./8.rs[]
----

== !

[source,rust]
----
include::./9.rs[]
----
