= Property Testing

link:./index.html[Table of Contents]


== This is your brain

-   Everything we know is subject to bias
-   Everything we build reflects these biases

== Problem:

Our code reflects our biases, our tests are often biased similarly

== Solution:

Don't write tests

== Solution:

Write expectations

== !

-   Have the machine generate random test cases
-   Make beliefs explicit, force them to pay rent

== !

This is called property testing

== Crate: **proptest**

[source,rust]
----
include::./1.rs[]
----

== Crate: **proptest**
[source, bash]
--
include::./2.txt[]
--

== Crate: **proptest**

[source, bash]
--
include::./3.txt[]
--

== !

Wonderful for testing codecs, serialization,
compression, or any set of operations that
should retain equality.

[source,rust]
----
include::./4.rs[]
----

== !

It's easy to generate more structured input, too

[source,rust]
----
include::./5.rs[]
----

== Configuration is a great target

[source,rust]
----
include::./6.rs[]
----

== Miscellaneous Tips

-   Isolate business logic from IO concerns
-   Use assert! and debug_assert! on non-trivial things! this makes our "fuzzers" extremely effective
-   Try not to use unwrap() everywhere, at least use expect("helpful message") to speed up debugging
-   When propagating errors, include context that helps you get back to the root

== !

Try it out!
