---

name: GitHub Pages
on:
  # The website will be deployed when any of these branches is pushed to:
  push:
    branches:
      - main
      - training_material_wip
  # Perform builds without uploads for pull requests:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch:
          - main
          - training_material_wip

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: "${{ matrix.branch }}"

      - name: Set up Ruby 2.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Node dependencies
        run: npm ci

      - name: Build
        run: PATH="$(pwd)/node_modules/.bin:$PATH" ./rake

      - name: Upload content
        uses: actions/upload-artifact@v3
        with:
          name: "content-${{ matrix.branch }}"
          path: target/
          retention-days: 1
