= Standard Types
:revealjs_width: 1920
:revealjs_height: 1080
:source-highlighter: highlightjs

link:./index.html[Table of Contents]


== !

There several pervasive types in Rust.

They leverage the powerful type system to accomplish fundamental tasks.

== Overview

-   `Option<T>` - Removes the need for a `null` primitive.
-   `Result<T,E>` - Removes the need for exceptions.
-   `Vec<T>` - Growable arrays.
-   `HashMap<K,V>` - Key value storage.

== `Option<T>`

[source,rust]
----
include::./1.rs[]
----
Options are wrapper types, and need to be unwrapped to be used.

== `Option<T>`

Any function which does not always return a value returns an `Option<T>`.

[source,rust]
----
include::./2.rs[]
----

== `Option<T>`: Benefit

The programmer *always* knows where a `None` may appear, and is able to decide how the situation should be handled.

This characteristic helps *remove mystery* from the coding process, and aids in confidence.

== `Option<T>`: Unwrapping

`unwrap()` will panic the application if the value is `None`.

This is only recommended in testing and prototyping.

[source,rust]
----
include::./3.rs[]
----

== `Option<T>`: Safety

`match` is one of several ways to safety work with `Option`s.

[source,rust]
----
include::./4.rs[]
----
No matter what the value of `maybe_a_value`, the program will never crash.

== `Option<T>`: Questions

Does this type completely remove the need for a `null` primitive?

What are the benefits?

== `Result<T,E>`

[source,rust]
----
include::./5.rs[]
----
Results are wrapper types which either contain the successful value, or the error value.

== `Result<T,E>`: Using

Results can be handled via `unwrap()` just like `Option` types, and can be handled in the same ways.

[source,rust]
----
include::./6.rs[]
----
Handling complex error scenarios will be addressed in a later chapter.

== `Result<T,E>`: Questions

Does this type completely remove the need for exceptions?

What are the benefits?

== `Vec<T>`

Owned, mutable, growable arrays. Located on the heap.

[source,rust]
----
include::./7.rs[]
----

== `Vec<T>`: Creation

Create with `Vec::new()` or the `vec![]` macro.

[source,rust]
----
include::./8.rs[]
----

== `Vec<T>`: As a Slice

`Vec<T>` implements `Deref<Target=[T]`, so it can be easily used as a slice.

[source,rust]
----
include::./9.rs[]
----

== `HashMap<K,V>`

HashMaps are key value stores. Keys must implement `Hash`.

[source,rust]
----
include::./10.rs[]
----

== `HashMap<K,V>`: `entry()`

Manipulate a key's cooresponding entry in place.

[source,rust]
----
include::./11.rs[]
----

