= Borrowing

link:./index.html[Table of Contents]


== What you own, you can borrow

== !

Ownership provides a solid semantic base, but becomes impractical in for the long run.

== !

Reuse of data after a function call is not possible with ownership if the called function doesn't return the ownership to the value again.

== !

Let's borrow instead!

== !

[source,rust]
----
include::./1.rs[]
----

== !

[source]
----
include::./1.diagram[]
----

== !

Simple borrowing can happen as often as you want.

== !

What if we want to change the value?

== !

[source,rust]
----
include::./2.rs[]
----

== !

Mutable borrows are exclusive!

== The borrowing rules

Values can be:

* Borrowed immutably as often as you'd like
* Or mutably exactly once

Ownership remains in the calling context, as well as the deallocation.

== !

What does this save us from?

== Do you see a potential problem?

[source,rust]
----
include::./3.rs[]
----

== !

It follows:

* for every type `T` there is a type `&T`
* for every type `T` there is a type `&mut T`
* `&&T` is a valid type
* `& &mut T` not a valid type. Why?

== Borrows are References

That means that we need to dereference them from time to time.

[source,rust]
----
include::./4.rs[]
----
